[package]
name = "tools-cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "tools-cli"
path = "src/main.rs"

[dependencies]
anyhow = "1"
tokio = { version = "1", features = ["full"] }
owo-colors = "4"
dialoguer = { version = "0.12.0", features = ["fuzzy-select"] }
serde_json = "1"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "http2", "json"] }

# remplace par tes vrais crates locaux
pms-core = { path = "../pms-core" }
pms-server = { path = "../pms-server" }
pms-storage = { path = "../pms-storage" }
pms-utils = { path = "../pms-utils" }
pms-types-block = { path = "../pms-types-block" }
pms-interface = { path = "../pms-interface" }
pms-config = { path = "../pms-config" }
pms-wire = { path = "../pms-wire" }
pms-wallet = { path = "../pms-wallet" }
pms-types = { path = "../pms-types" }
atty = "0.2.14"
qrcode = "0.14.1"
rand = "0.9.2"
futures = "0.3.31"
rust_decimal = { version = "1", features = ["serde", "serde-with-str"] }
rust_decimal_macros = "1.38.0"
rustls = { workspace = true }       # même si tu n'importes rien de rustls
hyper-rustls = { workspace = true } # si client HTTP
tokio-rustls = { workspace = true }
serde = { version = "1.0.226", features = ["derive"] }
hex = "0.4.3"